import type { Metadata } from "next";
import "./globals.css";
import Head from "next/head";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <body>
        <header>
          <Link href={"/"}>
            <div>
              Portfolio
            </div>
          </Link>
          <Link href={"/hw2"}>
            <div>
              Joke
            </div>
          </Link>
        </header>
        {children}
        <footer>
          Custom footer
        </footer>
      </body>
    </html>
  );
}